const KEY="ccc_v431_hist";
const EX={"Incline DB Press":["💪","30–45° bench, press to upper chest.","4","10",90],"Flat DB Press":["🏋️","Feet planted, steady press.","3","10",90],"Cable Fly":["🪽","Soft bend in elbows, squeeze chest.","3","15",60],"Rope Pushdown":["🔽","Pin elbows in, full extension.","4","12",60],"DB Curl":["💥","Keep elbows quiet, control down.","4","12",60],"Hammer Curl":["🔨","Neutral grip, slow lower.","3","15",60],"Chest Supported Row":["🚣","Chest down, squeeze shoulder blades.","4","10",75],"Lat Pulldown":["⬇️","Pull to upper chest, avoid swinging.","4","12",75],"Seated Cable Row":["↩️","Tall chest, pull elbows back.","3","12",75],"Face Pull":["🎯","Pull high, rotate thumbs back.","3","15",60],"Bird Dog":["🧠","Brace core, move slow.","3","10",45],"McGill Curl-Up":["🛡️","Lift slightly, no spinal crunch.","3","10",45],"Plank":["📏","Straight line, brace abs.","3","30 sec",45],"Leg Press":["🦵","Pain-free depth only.","4","12",90],"DB Romanian Deadlift":["⚙️","Hinge hips, neutral spine.","4","10",90],"Low Step-Ups":["📶","Low box, drive through heel.","3","10",60],"Hamstring Curl":["🧩","Control up and down.","3","15",60],"Calf Raise":["⬆️","Pause at top.","4","15",45],"Side Plank":["📐","Stack shoulders and hips.","3","30 sec",45],"Seated DB Shoulder Press":["🏛️","Stay tall, avoid back arch.","4","10",90],"Lateral Raise":["✈️","Lift to side, not shrug.","4","15",60],"Rear Delt Fly":["🪽","Open wide, squeeze rear delt.","4","15",60],"Farmer Carry":["🧳","Tall posture, slow steps.","5","rounds",60],"Pushups burnout":["🔥","Brace core, full-body plank.","1","burnout",60],"Curl burnout":["🔥","Controlled reps, no swinging.","1","burnout",60]};
const W=[["Day 1 — Chest + Arms","Upper chest, triceps, biceps",["Incline DB Press 4x10","Flat DB Press 3x10","Cable Fly 3x15","Rope Pushdown 4x12","DB Curl 4x12","Hammer Curl 3x15"]],["Day 2 — Back + Core","Back strength, posture, spine stability",["Chest Supported Row 4x10","Lat Pulldown 4x12","Seated Cable Row 3x12","Face Pull 3x15","Bird Dog 3 rounds","McGill Curl-Up 3 rounds","Plank 3x30 sec"]],["Day 3 — Legs Safe Mode","Knee-friendly lower body",["Leg Press 4x12","DB Romanian Deadlift 4x10","Low Step-Ups 3x10","Hamstring Curl 3x15","Calf Raise 4x15","Side Plank 3 rounds"]],["Day 4 — Wayne Armor","Shoulders, carries, presence",["Seated DB Shoulder Press 4x10","Lateral Raise 4x15","Rear Delt Fly 4x15","Farmer Carry 5 rounds","Pushups burnout","Curl burnout"]]];
let s=null,timer=null,rest=90;
const $=id=>document.getElementById(id);
function base(x){return x.replace(/\s+\d+x\d+$/,'').replace(/\s+x\d+$/,'').replace(/\s+rounds$/,'')}
function meta(x){return EX[base(x)]||["🎬","See example link for form.","1","work",60]}
function link(x){return `https://www.youtube.com/results?search_query=${encodeURIComponent(base(x)+" proper form")}`}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.t).classList.add('active')});
function render(){ $('list').innerHTML=W.map((w,i)=>`<div class="work"><div class="row"><div><div class="big">${w[0]}</div><div class="small">${w[1]}</div></div><div class="badge">${w[2].length} exercises</div></div>${w[2].map(x=>`<div class="step">${x}</div>`).join('')}<button class="go" data-i="${i}" style="margin-top:12px;width:100%">Start Session</button></div>`).join(''); document.querySelectorAll('.go').forEach(b=>b.onclick=()=>start(Number(b.dataset.i))); hist(); }
function start(i){const w=W[i]; s={name:w[0],items:w[2].map(x=>{const m=meta(x);return {name:base(x),icon:m[0],cue:m[1],sets:m[2],reps:m[3],rest:m[4],link:link(x)}}),idx:0,done:[]}; $('empty').classList.add('hidden'); $('card').classList.remove('hidden'); document.querySelector('[data-t="session"]').click(); ui();}
function ui(){const e=s.items[s.idx]; $('wname').textContent=s.name; $('prog').textContent=`${s.idx+1} / ${s.items.length}`; $('icon').textContent=e.icon; $('ename').textContent=e.name; $('cue').textContent=e.cue; $('watch').href=e.link; $('target').textContent=`${e.sets} x ${e.reps}`; rest=e.rest||60; showRest(); $('status').textContent=`Completed: ${s.done.length}`;}
function showRest(){ $('rest').textContent=`${String(Math.floor(rest/60)).padStart(2,'0')}:${String(rest%60).padStart(2,'0')}`; }
function next(skip){const e=s.items[s.idx]; s.done.push({name:e.name,skip}); if(s.idx<s.items.length-1){s.idx++; ui();} else finish();}
function finish(){clearInterval(timer); const h=JSON.parse(localStorage.getItem(KEY)||'[]'); h.push({date:new Date().toISOString().slice(0,10),name:s.name,total:s.items.length,completed:s.done.filter(x=>!x.skip).length,exerciseNames:s.done.filter(x=>!x.skip).map(x=>x.name)}); localStorage.setItem(KEY,JSON.stringify(h)); $('status').textContent=`Workout complete: ${s.name}`; s=null; hist();}
function hist(){const h=JSON.parse(localStorage.getItem(KEY)||'[]').reverse(); $('hlist').innerHTML=h.length?h.map(x=>`<div class="step"><div class="row"><div><div class="med">${x.name}</div><div class="small">${x.date}</div></div><div class="badge">${x.completed}/${x.total}</div></div><div class="small" style="margin-top:8px">${x.exerciseNames.join(', ')}</div></div>`).join(''):'<div class="small">No completed workouts yet.</div>'}
$('doneBtn').onclick=()=>s&&next(false); $('skipBtn').onclick=()=>s&&next(true); $('finishBtn').onclick=()=>s&&finish(); $('restBtn').onclick=()=>{clearInterval(timer); timer=setInterval(()=>{if(rest>0){rest--; showRest()} else {clearInterval(timer); $('status').textContent='Rest done.'}},1000)};
render();
