const CK='ccc_v44_checkins', WK='ccc_v44_workouts';
const EX={"Incline DB Press":["💪","30–45° bench, press to upper chest.","4","10",90],"Flat DB Press":["🏋️","Feet planted, steady press.","3","10",90],"Cable Fly":["🪽","Soft bend in elbows, squeeze chest.","3","15",60],"Rope Pushdown":["🔽","Pin elbows in, full extension.","4","12",60],"DB Curl":["💥","Keep elbows quiet, control down.","4","12",60],"Hammer Curl":["🔨","Neutral grip, slow lower.","3","15",60],"Chest Supported Row":["🚣","Chest down, squeeze shoulder blades.","4","10",75],"Lat Pulldown":["⬇️","Pull to upper chest, avoid swinging.","4","12",75],"Seated Cable Row":["↩️","Tall chest, pull elbows back.","3","12",75],"Face Pull":["🎯","Pull high, rotate thumbs back.","3","15",60],"Bird Dog":["🧠","Brace core, move slow.","3","10",45],"McGill Curl-Up":["🛡️","Lift slightly, no spinal crunch.","3","10",45],"Plank":["📏","Straight line, brace abs.","3","30 sec",45],"Leg Press":["🦵","Pain-free depth only.","4","12",90],"DB Romanian Deadlift":["⚙️","Hinge hips, neutral spine.","4","10",90],"Low Step-Ups":["📶","Low box, drive through heel.","3","10",60],"Hamstring Curl":["🧩","Control up and down.","3","15",60],"Calf Raise":["⬆️","Pause at top.","4","15",45],"Side Plank":["📐","Stack shoulders and hips.","3","30 sec",45],"Seated DB Shoulder Press":["🏛️","Stay tall, avoid back arch.","4","10",90],"Lateral Raise":["✈️","Lift to side, not shrug.","4","15",60],"Rear Delt Fly":["🪽","Open wide, squeeze rear delt.","4","15",60],"Farmer Carry":["🧳","Tall posture, slow steps.","5","rounds",60],"Pushups burnout":["🔥","Brace core, full-body plank.","1","burnout",60],"Curl burnout":["🔥","Controlled reps, no swinging.","1","burnout",60],"Goblet Squat":["🏺","Hold weight high, pain-free depth.","3","12",60],"Treadmill incline walk":["🚶","Steady pace, chest up.","1","10 min",0],"Bodyweight box squat":["📦","Sit back to box, stand tall.","3","12",45],"Brisk walk":["🚶","Fast pace, relaxed shoulders.","1","10 min",0],"Glute Bridge":["🌉","Drive hips up, squeeze glutes.","3","15",45]};
const HOME=[["Day 1 — Chest + Arms","Upper chest, triceps, biceps",["Incline DB Press 4x10","Flat DB Press 3x10","Cable Fly 3x15","Rope Pushdown 4x12","DB Curl 4x12","Hammer Curl 3x15"]],["Day 2 — Back + Core","Back strength, posture, spine stability",["Chest Supported Row 4x10","Lat Pulldown 4x12","Seated Cable Row 3x12","Face Pull 3x15","Bird Dog 3 rounds","McGill Curl-Up 3 rounds","Plank 3x30 sec"]],["Day 3 — Legs Safe Mode","Knee-friendly lower body",["Leg Press 4x12","DB Romanian Deadlift 4x10","Low Step-Ups 3x10","Hamstring Curl 3x15","Calf Raise 4x15","Side Plank 3 rounds"]],["Day 4 — Wayne Armor","Shoulders, carries, presence",["Seated DB Shoulder Press 4x10","Lateral Raise 4x15","Rear Delt Fly 4x15","Farmer Carry 5 rounds","Pushups burnout","Curl burnout"]]];
const TRAVEL={hotel:["Hotel Gym","Fast full body",["Flat DB Press 3x12","Goblet Squat 3x12","Chest Supported Row 3x12","Seated DB Shoulder Press 3x10","Treadmill incline walk 10 min"]],bodyweight:["No Equipment","Mobility + sweat",["Pushups burnout","Bodyweight box squat 3x12","Bird Dog 3x10","McGill Curl-Up 3x10","Brisk walk 10 min"]],recovery:["Recovery Day","Travel reset",["Bird Dog x10","McGill Curl-Up x10","Glute Bridge x15","Brisk walk 10 min"]]};
let s=null,timer=null,rest=90;
const $=id=>document.getElementById(id);
function base(x){return x.replace(/\s+\d+x\d+$/,'').replace(/\s+x\d+$/,'').replace(/\s+rounds$/,'')}
function meta(x){return EX[base(x)]||["🎬","See example link for form.","1","work",60]}
function link(x){return `https://www.youtube.com/results?search_query=${encodeURIComponent(base(x)+" proper form")}`}
function gc(){return JSON.parse(localStorage.getItem(CK)||'[]')} function sc(v){localStorage.setItem(CK,JSON.stringify(v))}
function gw(){return JSON.parse(localStorage.getItem(WK)||'[]')} function sw(v){localStorage.setItem(WK,JSON.stringify(v))}
function today(){return new Date().toISOString().slice(0,10)}
function ready(e){if(!e)return 0;const p=Math.min(Number(e.protein||0)/190,1)*25,s=Math.min(Number(e.steps||0)/8000,1)*20,en=(Math.min(Number(e.energy||0),10)/10)*20,b=((10-Math.min(Number(e.backPain||0),10))/10)*17.5,k=((10-Math.min(Number(e.kneePain||0),10))/10)*17.5;return Math.round(p+s+en+b+k)}
function coach(e,r){if(!e)return"Start by saving your first check-in.";const b=Number(e.backPain||0),k=Number(e.kneePain||0);if(b>=6)return"Back is flaring up. Use recovery mode today.";if(k>=6)return"Knee is talking. Keep depth shallow and reduce load.";if(r>=80)return"Green light. Push the main lift hard today.";if(r>=65)return"Solid day. Hit the session and keep a rep or two in reserve.";return"Recovery emphasis today. Steps, protein, and easier work."}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.t||b.dataset.tab).classList.add('active')});
function chart(canvas,data,key,color){const ctx=canvas.getContext('2d'),w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,w,h);const s=[...data].sort((a,b)=>(a.date||'').localeCompare(b.date||'')).slice(-10),vals=s.map(d=>Number(d[key]||0)).filter(v=>v>0);if(!vals.length){ctx.fillStyle='#94a3b8';ctx.font='14px sans-serif';ctx.fillText('No data yet',16,28);return}const min=Math.min(...vals),max=Math.max(...vals),range=Math.max(max-min,1);ctx.strokeStyle='rgba(255,255,255,.08)';for(let i=0;i<4;i++){const y=20+(h-40)*(i/3);ctx.beginPath();ctx.moveTo(10,y);ctx.lineTo(w-10,y);ctx.stroke()}ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();s.forEach((d,i)=>{const v=Number(d[key]||0),x=16+((w-32)*(s.length===1?0.5:i/(s.length-1))),y=h-18-(((v-min)/range)*(h-40));if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke()}
function renderHome(){const c=gc(),e=[...c].sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0],r=ready(e);$('readinessPill').textContent=`${r}%`;$('readinessBar').style.width=`${r}%`;$('coachMessage').textContent=coach(e,r);$('statWeight').textContent=e?.weight?`${e.weight} lb`:'--';$('statWaist').textContent=e?.waist?`${e.waist} in`:'--';$('statProtein').textContent=e?.protein?`${e.protein} g`:'--';$('statSteps').textContent=e?.steps||'--';$('sumEntries').textContent=c.length;const avg=k=>{const v=c.map(x=>Number(x[k]||0)).filter(n=>n>0);return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0};$('sumProtein').textContent=avg('protein');$('sumSteps').textContent=avg('steps');$('sumWorkouts').textContent=gw().length;chart($('weightChart'),c,'weight','#f59e0b')}
function save(){const x={date:$('date').value||today(),weight:$('weight').value,waist:$('waist').value,protein:$('protein').value,steps:$('steps').value,backPain:$('backPain').value,kneePain:$('kneePain').value,energy:$('energy').value,notes:$('notes').value};const c=gc();c.push(x);sc(c);$('saveStatus').textContent=`Saved ${x.date}.`;renderHome();renderHistory()}
function clearF(){$('date').value=today();['weight','waist','protein','steps','backPain','kneePain','energy','notes'].forEach(id=>$(id).value='');$('saveStatus').textContent=''}
function wcard(w,src,key=''){const m=meta(w[2][0]);const links=w[2].map(x=>`<a class="link" href="${link(x)}" target="_blank">${base(x)}</a>`).join(' ');return `<div class="work"><div class="row"><div><div class="title">${w[0]}</div><div class="small">${w[1]}</div></div><div class="badge">${w[2].length} ex</div></div><div class="icon">${m[0]}</div><div class="hint">${m[1]}</div>${w[2].map(x=>`<div class="step">${x}</div>`).join('')}<div style="margin-top:10px">${links}</div><button class="start" data-source="${src}" data-key="${key}" data-name="${w[0]}" style="margin-top:12px;width:100%">Start Session</button></div>`}
function renderTrain(){$('trainList').innerHTML=HOME.map(w=>wcard(w,'home')).join('');bindStarts()}
function renderTravel(){const k=$('travelSelect').value;$('travelWorkout').innerHTML=wcard(TRAVEL[k],'travel',k);bindStarts()}
function bindStarts(){document.querySelectorAll('.start').forEach(b=>b.onclick=()=>{let w;if(b.dataset.source==='home'){w=HOME.find(x=>x[0]===b.dataset.name)}else{w=TRAVEL[b.dataset.key]}startS(w)})}
function startS(w){s={name:w[0],items:w[2].map(x=>{const m=meta(x);return {name:base(x),icon:m[0],cue:m[1],sets:m[2],reps:m[3],rest:m[4],link:link(x)}}),idx:0,done:[]};$('sessionEmpty').classList.add('hidden');$('sessionCard').classList.remove('hidden');document.querySelector('[data-t="session"]')?.click();upd()}
function upd(){const e=s.items[s.idx];$('sessionWorkout').textContent=s.name;$('sessionProgress').textContent=`${s.idx+1} / ${s.items.length}`;$('sessionIcon').textContent=e.icon;$('sessionExercise').textContent=e.name;$('sessionCue').textContent=e.cue;$('sessionWatch').href=e.link;$('sessionTarget').textContent=`${e.sets} x ${e.reps}`;rest=e.rest||60;showRest();$('sessionStatus').textContent=`Completed: ${s.done.length}`}
function showRest(){$('restDisplay').textContent=`${String(Math.floor(rest/60)).padStart(2,'0')}:${String(rest%60).padStart(2,'0')}`}
function restStart(){clearInterval(timer);timer=setInterval(()=>{if(rest>0){rest--;showRest()}else{clearInterval(timer);$('sessionStatus').textContent='Rest done.'}},1000)}
function next(skip){const e=s.items[s.idx];s.done.push({name:e.name,skip});if(s.idx<s.items.length-1){s.idx++;upd()}else finish()}
function finish(){clearInterval(timer);const h=gw();h.push({date:today(),name:s.name,total:s.items.length,completed:s.done.filter(x=>!x.skip).length,exerciseNames:s.done.filter(x=>!x.skip).map(x=>x.name)});sw(h);$('sessionStatus').textContent=`Workout complete: ${s.name}`;s=null;renderHome();renderHistory()}
function renderHistory(){const c=[...gc()].reverse();$('checkinHistory').innerHTML=c.length?c.map(x=>`<div class="hist"><div class="row"><div><div class="value">${x.date}</div><div class="small">${x.notes||''}</div></div><div class="badge">${ready(x)}%</div></div><div class="small" style="margin-top:8px">Wt ${x.weight||'--'} · Waist ${x.waist||'--'} · Protein ${x.protein||'--'} · Steps ${x.steps||'--'}</div></div>`).join(''):'<div class="small">No check-ins yet.</div>';const h=[...gw()].reverse();$('workoutHistory').innerHTML=h.length?h.map(x=>`<div class="hist"><div class="row"><div><div class="value">${x.name}</div><div class="small">${x.date}</div></div><div class="badge">${x.completed}/${x.total}</div></div><div class="small" style="margin-top:8px">${x.exerciseNames.join(', ')}</div></div>`).join(''):'<div class="small">No completed workouts yet.</div>'}
function exportJ(){const blob=new Blob([JSON.stringify({checkins:gc(),workouts:gw()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ccc_v44_data.json';a.click();URL.revokeObjectURL(url)}
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{$(b.dataset.fill).value=b.dataset.value});
$('saveBtn').onclick=save;$('clearFormBtn').onclick=clearF;$('travelSelect').onchange=renderTravel;$('restBtn').onclick=restStart;$('doneBtn').onclick=()=>s&&next(false);$('skipBtn').onclick=()=>s&&next(true);$('finishBtn').onclick=()=>s&&finish();$('exportBtn').onclick=exportJ;
$('date').value=today();renderTrain();renderTravel();renderHome();renderHistory();
